version: '3.9'

services:
  employees-service.db:
    image: postgres:latest
    container_name: employees-service.db
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/employees-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s

  employees-service.api:
    image: ${DOCKER_REGISTRY-}employees-service.api
    container_name: employees-service.api
    build:
      context: .
      dockerfile: EmployeesService.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://employees-service.seq:5341/ingest/otlp/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    depends_on:
      employees-service.db:
        condition: service_healthy

  employees-service.seq:
    image: datalust/seq:latest
    container_name: employees-service.seq
    volumes:
      - ./.containers/seq:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true 
    ports:
      - 5341:5341
      - 8081:80