name: Build Solution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/EmployeesService.sln

    - name: Build
      run: dotnet build src/EmployeesService.sln --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test src/EmployeesService.Tests/EmployeesService.Tests.csproj --no-build --configuration Release

    - name: Publish API
      run: dotnet publish src/EmployeesService.Api/EmployeesService.Api.csproj -c Release -o publish